<script src="{{asset('assets/app/lib/jquery/js/jquery.js')}}"></script>
<script src="{{asset('assets/app/lib/popper.js/js/popper.js')}}"></script>
<script src="{{asset('assets/app/lib/bootstrap/js/bootstrap.js')}}"></script>
<script src="{{asset('assets/app/lib/jquery.cookie/js/jquery.cookie.js')}}"></script>
<script src="{{asset('assets/app/lib/chartist/js/chartist.js')}}"></script>
<script src="{{asset('assets/app/lib/d3/js/d3.js')}}"></script>
<!-- <script src="{{asset('assets/app/lib/rickshaw/js/rickshaw.min.js')}}"></script> -->
<script src="{{asset('assets/app/lib/jquery.sparkline.bower/js/jquery.sparkline.min.js')}}"></script>
<script src="{{asset('assets/app/lib/datatables/js/jquery.dataTables.js')}}"></script>
<!-- <script src="{{asset('assets/app/lib/datatables-responsive/js/dataTables.responsive.js')}}"></script> -->
<script src="{{asset('assets/app/lib/select2/js/select2.min.js')}}"></script>
<script src="{{asset('assets/app/lib/parsleyjs/js/parsley.js')}}"></script>
<script src="{{asset('assets/app/lib/jquery.maskedinput/js/jquery.maskedinput.js')}}"></script>
<script src="{{asset('assets/app/lib/jquery-ui/js/jquery-ui.js')}}"></script>
<script src="{{asset('assets/app/lib/jt.timepicker/js/jquery.timepicker.js')}}"></script>
<script src="{{asset('assets/app/lib/moment/min/moment.min.js')}}"></script>
<script src="{{asset('assets/app/lib/bootstrap-daterangepicker/daterangepicker.js')}}"></script>
<script src="{{asset('assets/app/lib/lightbox2/js/lightbox.js')}}"></script>
<script src="{{asset('assets/app/lib/fileuploader/js/jquery.modal.min.js')}}"></script>
<script src="{{asset('assets/app/lib/fileuploader/js/jquery.slick.min.js')}}"></script>
<script src="{{asset('assets/app/lib/fileuploader/js/main.js')}}"></script>
<script src="{{asset('assets/app/lib/lobibox/js/lobibox.js')}}"></script>
<!-- <script src="https://cdn.ckeditor.com/ckeditor5/12.4.0/classic/ckeditor.js"></script> -->
<script src="{{asset('assets/app/lib/summernote/dist/summernote-lite.js')}}"></script>
<script src="{{asset('assets/app/lib/tiny/tinymce.min.js')}}"></script>
@yield('js')
<script src="{{asset('assets/app/js/ResizeSensor.js')}}"></script>
<script src="{{asset('assets/app/js/slim.js')}}"></script>
<script src="{{asset('assets/build/admin/js/changePass.js')}}"></script>
<script> var base_admin = '{{ url('/') }}'</script>